services:
  backend_spring_server:
    build: .
    container_name: backend_spring_server
    restart: unless-stopped
    networks:
      - connect-gnu-network
networks:
  connect-gnu-network:
    external: true
