services:
  connect-gnu-spring:
    build: .
    image: dongho18/connect-gnu-spring:latest
    container_name: connect-gnu-spring
    restart: unless-stopped
    networks:
      - connect-gnu-network
    environment:
      TZ: "Asia/Seoul"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
        reservations:
          memory: 256m
          cpus: "0.25"
networks:
  connect-gnu-network:
    external: true
