services:
  backend_spring_server:
    build: .
    container_name: backend_spring_server
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/application.properties
    volumes:
      - ./src/main/resources/application.properties:/src/main/resources/application.properties