services:
  connect-gnu-spring:
    image: dongho18/connect-gnu-spring:latest
    pull_policy: always
    container_name: connect-gnu-spring
    restart: unless-stopped
    networks:
      - connect-gnu-network
    environment:
      - spring.config.additional-location=file:/app/application.properties
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Xms128m -Xmx512m -XX:+UseSerialGC -XX:+ExitOnOutOfMemoryError
    volumes:
      - ./application.properties:/app/application.properties
      - ./dumps:/dumps
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
        reservations:
          memory: 256m
          cpus: "0.25"

networks:
  connect-gnu-network:
    external: true
