services:
  backend_spring_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_spring_server
    restart: unless-stopped
    ports:
      - 5100:5100
    environment:
      TZ: "Asia/Seoul"