services:
  connect-gnu-spring:
    image: dongho18/connect-gnu-spring:latest
    pull_policy: always
    container_name: connect-gnu-spring
    restart: unless-stopped
    networks:
      - connect-gnu-network
    environment:
      - spring.config.additional-location=file:/app/application.properties
      - TZ=Asia/Seoul
      - JAVA_OPTS=-server -Xms512m -Xmx512m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -Xloggc:/tmp/gc.log
    volumes:
      - ./application.properties:/app/application.properties
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

networks:
  connect-gnu-network:
    external: true
