services:
  backend_spring_server:
    build: .
    image: dongho18/connect-gnu-spring:latest
    container_name: backend_spring_server
    restart: unless-stopped
    networks:
      - connect-gnu-network
    environment:
      TZ: "Asia/Seoul"
    deploy:
      resources:
        limits:
          memory: 512Mi
          cpus: "0.5"
        reservations:
          memory: 256Mi
          cpus: "0.25"
networks:
  connect-gnu-network:
    external: true
